---
- name: Configure systemd overrides for Splunk
  when: systemd.splunk.override | default(false)
  become: true
  block:
    - name: Create systemd override directory for Splunk
      ansible.builtin.file:
        path: "/etc/systemd/system/{{ splunk_service }}.service.d"
        state: directory
        mode: "0755"
        owner: root
        group: root

    - name: Update the systemd override file for Splunk
      ansible.builtin.template:
        src: splunk_systemd_override.conf.j2
        dest: "/etc/systemd/system/{{ splunk_service }}.service.d/limits.conf"
        mode: "0644"
        owner: root
        group: root
      notify: reload systemctl daemon
