---
- name: Configure splunk.secret
  when: splunk_configure_secret
  block:
    - name: Install splunk.secret from variable
      ansible.builtin.copy:
        content: "{{ splunk_secret_content | trim }}"
        dest: "{{ splunk_home }}/etc/auth/splunk.secret"
        owner: "{{ splunk_nix_user }}"
        group: "{{ splunk_nix_group }}"
        mode: "0400"
      become: true
      notify: restart splunk
      no_log: true
      when: splunk_secret_content | trim | length > 0

    - name: Install splunk.secret from file
      ansible.builtin.copy:
        src: "{{ splunk_secret_file }}"
        dest: "{{ splunk_home }}/etc/auth/splunk.secret"
        owner: "{{ splunk_nix_user }}"
        group: "{{ splunk_nix_group }}"
        mode: "0400"
      become: true
      notify: restart splunk
      when: splunk_secret_content | trim | length == 0
