---
# This task MUST be called by configure_apps.yml to work correctly. Do NOT call this task directly via the deployment_task var!

# Note: By using the synchronize module, if the repo already exists on the target host, we are able to only update the diff while preserving the local/ folder
- name: "Synchronize {{ item.name }} repo from local Ansible host to {{ splunk_home }}/{{ app_dest }}/{{ item.name }} on remote host"
  ansible.posix.synchronize:
    src: "{{ app_src }}"
    dest: "{{ splunk_home }}/{{ app_dest }}/"
    recursive: true
    delete: true
    checksum: true
    private_key: "{{ rsync_private_key | default(omit) }}"
    rsync_opts:
      - "--prune-empty-dirs"
      - "--itemize-changes"
      - "--no-times"
  become: true
  become_user: "{{ splunk_nix_user }}"
  notify: "{{ handler }}"
